### PR TITLE
add page "Editors and IDEs"

### PR DESCRIPTION
**Pull request by yhu266**

### CODE REVIEW

**Comment by yhu266** [comment]
@francisdbillones @nullfact0r Would you review this PR?

**Comment by francisdbillones** [comment]
LGTM! I'll add descriptions for the extra text editors after the fact.

**Comment by yhu266** [comment]
> LGTM! I'll add descriptions for the extra text editors after the fact.

Do you think we should change it to a table format? Would it be easier to arrange information and make it easier to compare?

**Comment by francisdbillones** [comment]
@yhu266 In my opinion, I don't think so. There isn't much quantitative data to be compared, so a table wouldn't really help. Would help with readability though. It's up to you, I'm fine with either.

**Pull request merged**
